changelog:
  categories:
    - title: "llama-index-workflows"
      labels:
        - "pkg:llama-index-workflows"
    - title: "llama-index-utils-workflow"
      labels:
        - "pkg:llama-index-utils-workflow"
    - title: "Other"
      labels:
        - "*"
