apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-dev
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-dev
rules:
  - apiGroups: [""]
    resources: [nodes, nodes/metrics, services, endpoints, pods]
    verbs: [get, list, watch]
  - apiGroups: ["networking.k8s.io"]
    resources: [ingresses]
    verbs: [get, list, watch]
  - nonResourceURLs: ["/metrics"]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-dev
subjects:
  - kind: ServiceAccount
    name: prometheus-dev
    namespace: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: dev
  namespace: monitoring
spec:
  serviceAccountName: prometheus-dev
  replicas: 1
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: llama-agents
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
  retention: 1d
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    fsGroup: 0
