{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "llama-agents.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.rbac.roleAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: ['']
  resources: ['configmaps', 'secrets', 'serviceaccounts', 'services']
  verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['']
  resources: ['events']
  verbs: ['create', 'get', 'list', 'patch', 'watch']
- apiGroups: ['']
  resources: ['pods']
  verbs: ['get', 'list', 'watch']
- apiGroups: ['']
  resources: ['pods/log']
  verbs: ['get']
- apiGroups: ['apps']
  resources: ['deployments']
  verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['apps']
  resources: ['replicasets']
  verbs: ['get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['batch']
  resources: ['jobs']
  verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['coordination.k8s.io']
  resources: ['leases']
  verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['deploy.llamaindex.ai']
  resources: ['llamadeployments']
  verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
- apiGroups: ['deploy.llamaindex.ai']
  resources: ['llamadeployments/finalizers']
  verbs: ['update']
- apiGroups: ['deploy.llamaindex.ai']
  resources: ['llamadeployments/status']
  verbs: ['get', 'patch', 'update']
- apiGroups: ['deploy.llamaindex.ai']
  resources: ['llamadeploymenttemplates']
  verbs: ['get', 'list', 'watch']
- apiGroups: ['networking.k8s.io']
  resources: ['ingresses', 'networkpolicies']
  verbs: ['create', 'delete', 'get', 'list', 'patch', 'update', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "llama-agents.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.rbac.roleBindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "llama-agents.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "llama-agents.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
