{{- if .Values.s3proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llama-agents.s3proxy.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "llama-agents.controlplane.name" . }}
type: Opaque
data:
  {{- include "llama-agents.s3proxy.secretData" . | nindent 2 }}
{{- end }}
