//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaDeployment) DeepCopyInto(out *LlamaDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaDeployment.
func (in *LlamaDeployment) DeepCopy() *LlamaDeployment {
	if in == nil {
		return nil
	}
	out := new(LlamaDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LlamaDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaDeploymentList) DeepCopyInto(out *LlamaDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LlamaDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaDeploymentList.
func (in *LlamaDeploymentList) DeepCopy() *LlamaDeploymentList {
	if in == nil {
		return nil
	}
	out := new(LlamaDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LlamaDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaDeploymentSpec) DeepCopyInto(out *LlamaDeploymentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaDeploymentSpec.
func (in *LlamaDeploymentSpec) DeepCopy() *LlamaDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(LlamaDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaDeploymentStatus) DeepCopyInto(out *LlamaDeploymentStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.ReleaseHistory != nil {
		in, out := &in.ReleaseHistory, &out.ReleaseHistory
		*out = make([]ReleaseHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RolloutStartedAt != nil {
		in, out := &in.RolloutStartedAt, &out.RolloutStartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaDeploymentStatus.
func (in *LlamaDeploymentStatus) DeepCopy() *LlamaDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(LlamaDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaDeploymentTemplate) DeepCopyInto(out *LlamaDeploymentTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaDeploymentTemplate.
func (in *LlamaDeploymentTemplate) DeepCopy() *LlamaDeploymentTemplate {
	if in == nil {
		return nil
	}
	out := new(LlamaDeploymentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LlamaDeploymentTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaDeploymentTemplateList) DeepCopyInto(out *LlamaDeploymentTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LlamaDeploymentTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaDeploymentTemplateList.
func (in *LlamaDeploymentTemplateList) DeepCopy() *LlamaDeploymentTemplateList {
	if in == nil {
		return nil
	}
	out := new(LlamaDeploymentTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LlamaDeploymentTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LlamaDeploymentTemplateSpec) DeepCopyInto(out *LlamaDeploymentTemplateSpec) {
	*out = *in
	in.PodSpec.DeepCopyInto(&out.PodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LlamaDeploymentTemplateSpec.
func (in *LlamaDeploymentTemplateSpec) DeepCopy() *LlamaDeploymentTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(LlamaDeploymentTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReleaseHistoryEntry) DeepCopyInto(out *ReleaseHistoryEntry) {
	*out = *in
	in.ReleasedAt.DeepCopyInto(&out.ReleasedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReleaseHistoryEntry.
func (in *ReleaseHistoryEntry) DeepCopy() *ReleaseHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(ReleaseHistoryEntry)
	in.DeepCopyInto(out)
	return out
}
