[project]
name = "llama-index-utils-workflow"
version = "0.4.1"
description = "llama-index utils for workflows"
readme = "README.md"
authors = [{ name = "Adrian Lyjak", email = "adrianlyjak@gmail.com" }]
requires-python = ">=3.9"
dependencies = [
    "llama-index-core>=0.14,<0.15.0",
    "llama-index-workflows>=2.8.3,<3.0.0",
    "pyvis>=0.3.2",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/llama_index"]
