name: Publish utils to PyPI and GitHub

on:
  workflow_dispatch:
  push:
    tags:
      - "llama-index-utils-workflow@v*"

jobs:
  build-n-publish-utils:
    name: Build and publish utils to PyPI
    if: github.repository == 'run-llama/workflows-py'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build and publish utils package
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv build --package llama-index-utils-workflow
          uv publish
